#Chapter 01 파이썬 기반의 머신러닝과 생태계 이해
##01 머신러닝의 개념
---
애플리케이션을 수정하지 않고도 데이터를 기반으로 패턴을 학습하고 결과를 예측하는 알고리즘 기법

###머신러닝의 분류
- 지도학습 : 분류, 회귀, 추천시스템, 시각/음성 감지/인지, 텍스트 분석, NLP

- 비지도학습 : 클러스터링, 차원 축소, 강화학습

###데이터 전쟁
머신러닝은 데이터에 매우 의존적이기 때문에 좋은 품질의 데이터를 갖추지 못한다면 머신러닝의 수행 결과도 좋을 수 없다. 따라서, 데이터를 이해하고 효율적으로 가공, 처리, 추출해 최적의 데이터를 기반으로 알고리즘을 구동할 수 있도록 준비하는 능력이 중요하다.

##02 파이썬 머신러닝 생태계를 구성하는 주요 패키지
---
파이썬 기반의 머신러닝을 익히기 위해 필요한 패키지
- 머신러닝 패키지
- 행렬/선형대수/통계 패키지
- 데이터 핸들링
- 시각화

##03 넘파이
---
Numerical Python : 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지

- 빠른 배열 연산 속도 보장
- C/C++과 같은 저수준 언어 기반의 호환 API 제공
- 다양한 데이터 핸들링 기능 제공

###넘파이 ndarray 개요





In [ ]:
import numpy as np

넘파이의 기반 데이터 타입 : ndarray -> 다차원 배열을 쉽게 생성하고 다양한 연산 수행

array() 함수 : 파이썬의 리스트와 같은 다양한 인자를 입력받아 ndarray로 변환

생성된 ndarray 배열의 shape 변수는 ndarray의 크기, 즉 행과 열의 수를 튜플 형태로 가지고 있으며 이를 통해 ndarray 배열의 차원까지 알 수 있음

In [ ]:
array1=np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2=np.array([[1,2,3],[2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3=np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


np.array() : ndarray로 변환을 원하는 객체를 인자로 입력하면 ndarray를 반환

ndarray.shape : ndarray의 차원과 크기를 튜플 형태로 나타냄
- 1차원 : (보유 데이터 개수, )
- 2차원 : (로우 개수, 칼럼 개수)

In [ ]:
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3: 2차원


array() 함수의 인자로는 리스트 객체가 주로 사용됨

- 리스트 [] -> 1차원
- 리스트 [[]] -> 2차원

###ndarray의 데이터 타입
- 숫자형 : int형, unsigned int형, float형, complex타입
- 문자열 값
- 불 값

ndarray내의 데이터 타입은 같은 데이터 타입만 가능(dtype 속성으로 데이터 타입 확인)


In [ ]:
list1=[1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용
- int형과 문자열 -> 문자열
- int형과 float형 -> float형

In [ ]:
list2=[1,2, 'test']
array2=np.array(list2)
print(array2, array2.dtype)

list3=[1,2,3.0]
array3=np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


astype() : ndarray 내 데이터값의 타입 변경 -> 메모리 절약을 위해 이용

In [ ]:
array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1=array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1=np.array([1.1, 2.1, 3.1])
array_int2=array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


###ndarray를 편하게 생성하기 - arange, zeros, ones
테스트용으로 데이터를 만들거나 대규모의 데이터를 일괄적으로 초기화해야 할 경우 사용
- arange() : 0부터 함수 인자 값 -1까지의 값을 순차적으로 ndarray의 데이터값으로 변환
- zeros() : 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray를 반환
- ones() : 튜플 형태의 shape 값을 입력하면 모든 값을 1로 채운 해당 shape를 가진 ndarray로 반환

In [ ]:
sequence_array=np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

zero_array=np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)
[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


###ndarray의 차원과 크기를 변경하는 reshape()
reshape() 메서드 : ndarray를 특정 차원 및 크기로 변환(변환을 원하는 크기를 함수 인자로 부여)

In [ ]:
array1=np.arange(10)
print('array1:\n', array1)

array2=array1.reshape(2, 5)
print('array2:\n', array2)

array3=array1.reshape(5,2)
print('array3:\n', array3)

array1.reshape(4,3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


ValueError: cannot reshape array of size 10 into shape (4,3)

reshape()에서 인자로 -1을 사용하면 원래 ndarray와 호환되는 새로운 shape로 변환해 준다.

-1 인자는 reshape(-1,1)와 같은 형태로 자주 사용된다. reshape(-1,1)은 원본 ndarray가 어떤 형태라도 2차원이고, 여러 개의 로우를 가지되 반드시 1개의 칼럼을 가진 ndarray로 변환됨을 보장한다.

In [ ]:
array1=np.arange(10)
print(array1)
array2=array1.reshape(-1,5)
print('array2 shape:', array2.shape)
array3=array1.reshape(5,-1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [ ]:
array1=np.arange(10)
array4=array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

In [ ]:
array1=np.arange(8)
array3d=array1.reshape((2, 2, 2))
print('array3d:\n', array3d.tolist())

#3차원 ndarray를 2차원 ndarray로 변환
array5=array3d.reshape(-1, 1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6=array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


###넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)
인덱싱 : ndarray 내의 일부 데이터 세트나 특정 데이터만을 선택할 수 있도록 함

####단일 값 추출
1개의 데이터값을 선택하려면 ndarray 객체에 해당하는 위치의 인덱스 값을 [] 안에 입력

인덱스에 마이너스 기호를 이용하면 맨 뒤에서부터 데이터를 추출

In [ ]:
#1부터 9까지의 1차원 ndarray 생성
array1=np.arange(start=1, stop=10)
print('array1:',array1)
#index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value=array1[2]
print('value:', value)
print(type(value))

print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값', array1[-2])

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>
맨 뒤의 값: 9 맨 뒤에서 두 번째 값 8


In [ ]:
array1[0]=9
array1[8]=0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


다차원 ndarray에서 단일 값을 추출하는 경우 콤마로 분리된 로우와 칼럼 위치의 인덱스를 통해 접근한다.

axis 0은 로우 방향의 축을 axis 1은 칼럼 방향의 축을 의미한다.

In [ ]:
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3, 3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0, 0])
print('(row=0, col=1) index 가리키는 값:', array2d[0, 1])
print('(row=1, col=0) index 가리키는 값:', array2d[1, 0])
print('(row=2, col=2) index 가리키는 값:', array2d[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


####슬라이싱
':' 기호를 이용해 연속한 데이터를 슬라이싱해서 추출할 수 있다.

단일 데이터값 추출을 제외한 이외의 방법으로 추출된 데이터 세트는 모두 ndarray 타입이다.

':' 사이에 시작 인덱스와 종료 인덱스를 표시하면 시작 인덱스에서 종료 인덱스 -1의 위치에 있는 데이터의 ndarray를 반환한다. 시작, 종료 인덱스는 생략이 가능하다.


1.   ':' 기호 앞에 시작 인덱스를 생략하면 자동으로 맨 처음 인덱스인 0으로 간주한다.
2.   ':' 기호 뒤에 종료 인덱스를 생략하면 자동으로 맨 마지막 인덱스로 간주한다.
3.  ':' 기호 앞/뒤에 시작/종료 인덱스를 생략하면 자동으로 맨 처음/ 맨 마지막 인덱스로 간주한다.



In [ ]:
array1=np.arange(start=1, stop=10)
array3=array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
array1=np.arange(start=1, stop=10)
array4=array1[:3]
print(array4)

array5=array1[3:]
print(array5)

array6=array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


2차원 ndarray에서의 슬라이싱도 1차원 ndarray에서의 슬라이싱과 유사하며, 단지 콤마로 로우와 칼럼 인덱스를 지칭하는 부분만 다르다.

2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원 ndarray를 반환한다.

3차원 ndarray에서 뒤에 오는 인덱스를 없애면 2차원 ndarray를 반환한다.

In [ ]:
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3, 3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2]\n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3]\n', array2d[1:3, 0:3])
print('array2d[1:3, :]\n', array2d[1:3, :])
print('array2d[:, :]\n', array2d[:, :])
print('array2d[:2, 1:]\n', array2d[:2, 1:])
print('array2d[:2, 0]\n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]
 [[2 3]
 [5 6]]
array2d[:2, 0]
 [1 4]


In [ ]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


####팬시 인덱싱
: 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식

In [ ]:
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3, 3)

array3=array2d[[0, 1], 2]
print('array2d[[0, 1], 2] =>', array3.tolist())

array4=array2d[[0, 1], 0:2]
print('array2d[[0,1], 0:2] =>', array4.tolist())

array5=array2d[[0, 1]]
print('array2d[[0, 1]] =>', array5.tolist())

array2d[[0, 1], 2] => [3, 6]
array2d[[0,1], 0:2] => [[1, 2], [4, 5]]
array2d[[0, 1]] => [[1, 2, 3], [4, 5, 6]]


####불린 인덱싱
조건 필터링과 검색을 동시에 할 수 있기 때문에 매우 자주 사용되는 인덱싱 방식

ndarray의 인덱스를 지정하는 [] 내에 조건문을 그대로 기재하여 for loop/if else 문보다 훨씬 간단히 구현할 수 있음

In [ ]:
array1d=np.arange(start=1, stop=10)
#[ ] 안에 array1d>5 Boolean indexing을 적용
array3=array1d[array1d>5]
print('array1d>5 불린 인덱싱 결과 값 :', array3)

array1d>5 불린 인덱싱 결과 값 : [6 7 8 9]


In [ ]:
array1d>5

array([False, False, False, False, False,  True,  True,  True,  True])

ndarray 객체에 조건식만 붙이면 False, True로 이뤄진 ndarray 객체가 반환된다. 조건으로 반환된 이 ndarray 객체를 인덱싱을 지정하는 []내에 입력하면 False 값은 무시하고 True 값이 있는 위치 인덱스 값으로 자동 변환해 해당하는 인덱스 위치의 데이터만 반환한다.

In [ ]:
boolean_indexes=np.array([False, False, False, False, False, True, True, True, True])
array3=array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [ ]:
indexes=np.array([5, 6, 7, 8])
array4=array1d[indexes]
print('일반 인덱스로 필터링 결과 :', array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


불린 인덱싱이 동작하는 단계
1. array1d>5와  같이 ndarray의 필터링 조건을 [] 안에 기재
2. False 값은 무시하고 True 값에 해당하는 인덱스 값만 저장(True값 자체인 1을 저장하는 것이 아닌 True값을 가진 인덱스를 저장)
3. 저장된 인덱스 데이터 세트로 ndarray 조회

###행렬의 정렬 - sort()와 argsort()
####행렬 정렬
- np.sort() : 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환
- ndarray.sort() : 원 행렬 자체를 정렬한 형태로 변환하며 반환 값은 None

기본적으로 오름차순으로 행렬 내 원소 정렬

내림차순으로 정렬하기 위해서는 [::-1]을 적용

In [ ]:
org_array=np.array([3, 1, 9, 5])
print('원본 행렬:', org_array)
#np.sort()로 정렬
sort_array1=np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬 :', sort_array1)
print('np.sort() 호출 후 원본 행렬 :', org_array)
#ndarray.sort()로 정렬
sort_array2=org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬 :', sort_array2)
print('org_array.sort() 호출 후 원본 행렬 :', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬 : [1 3 5 9]
np.sort() 호출 후 원본 행렬 : [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬 : None
org_array.sort() 호출 후 원본 행렬 : [1 3 5 9]


In [ ]:
sort_array1_desc=np.sort(org_array)[::-1]
print('내림차순으로 정렬 :', sort_array1_desc)

내림차순으로 정렬 : [9 5 3 1]


행렬이 2차원 이상일 경우 axis 축 값 설정을 통해 로우 또는 칼럼 방향으로 정렬을 수행

In [ ]:
array2d=np.array([[8, 12],[7, 1]])
sort_array2d_axis0=np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1=np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


####정렬된 행렬의 인덱스를 반환하기
np.argsort() : 원본 행렬이 정렬되었을 때 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때 이용, 정렬 행렬의 원본 행렬 인덱스를 ndarray 형으로 반환

내림차순으로 정렬 시에 원본 행렬의 인덱스를 구하려면 [::-1] 적용

In [ ]:
org_array=np.array([3, 1, 9, 5])
sort_indices=np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스 :', sort_indices)

org_array=np.array([3, 1, 9, 5])
sort_indices_desc=np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스 :', sort_indices_desc)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스 : [1 0 3 2]
행렬 내림차순 정렬 시 원본 행렬의 인덱스 : [2 3 0 1]


넘파이의 ndarray는 메타 데이터를 가질 수 없다. 따라서 실제 값과 그 값이 뜻하는 메타 데이터를 별도의 ndarray로 각각 가져야 한다. 이때, np.argsort를 이용해 데이터를 추출할 수 있다.

In [ ]:
import numpy as np

name_array=np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array=np.array([78, 95, 84, 98, 88])

sort_indices_asc=np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스 :', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력 :', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스 : [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력 : ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


###선형대수 연산 - 행렬 내적과 전치 행렬 구하기
####행렬 내적(행렬 곱)
np.dot() : 두 행렬 A와 B의 내적 계산

두 행렬 A와 B의 내적은 왼쪽 행렬의 로우(행)와 오른쪽 행렬의 칼럼(열)의 원소들을 순차적으로 곱한 뒤 그 결과를 모두 더한 값이다.

행렬의 내적 연산은 왼쪽 행렬의 열 개수와 오른쪽 행렬의 행 개수가 동일해야 가능하다.

In [ ]:
A=np.array([[1, 2, 3],[4, 5, 6]])
B=np.array([[7, 8],[9, 10],[11, 12]])
dot_product=np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


####전치 행렬
: 원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬

In [ ]:
A=np.array([[1, 2], [3, 4]]),
transpose_mat=np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[[1]
  [3]]

 [[2]
  [4]]]
