<a href="https://colab.research.google.com/github/seo104/26-2-ESAA/blob/main/YB_0904_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [17]:
A = np.ones((5,3))
B = np.ones((3,2))
result = np.dot(A,B)

print(result)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [18]:
array = np.arange(11)
print('원본 :', array)

array[(array>3)&(array<8)]*=-1
print('변경 후 :', array)

원본 : [ 0  1  2  3  4  5  6  7  8  9 10]
변경 후 : [ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [19]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


1. 파이썬 내장 sum의 경우 마지막 인자가 시작값이기 때문에 -1+0+1+2+3+4=9
2. numpy 내장함수는 두번째 인 -1이 axis=-1을 의미하기 때문에 0+1+2+3+4=10

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

Z < Z > Z

NumPy 배열에서는 연속 비교의 결과가 Boolean 배열이 되기 때문에, 이를 하나의 True/False로 판단할 수 없어 오류가 발생한다.

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

1. 0으로 나눌 수 없기 때문에 nan 값이 나옴
2. //는 정수 나눗셈, 정수형에는 nan이 없어서 0 반환
3. nan을 정수로 잘못 표현해서 실수로 변환

In [21]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/tmp/ipykernel_487/3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipykernel_487/3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipykernel_487/3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [22]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1)
print(Z2)
common = np.intersect1d(Z1,Z2)
print(common)

[5 8 8 4 6 4 7 0 2 1]
[9 8 7 9 9 0 5 5 2 9]
[0 2 5 7 8]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

False. nan!=1j


np.sart()는 실수 영역에서의 제곱근을 계산하기 때문에 -1을 넣어 계산하면 nan 값이 나오고 np.emath.sqrt()는 복소수영역까지 다루기 때문에 -1을 넣었을 때, 1j가 나와 서로 출력값이 같지 않다.

In [23]:
np.sqrt(-1) == np.emath.sqrt(-1)

/tmp/ipykernel_487/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [7]:
Z=np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [24]:
A=np.random.random((3,3))
B=np.random.random((3,3))
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([[-0.41948208, -0.87072692, -0.05221369],
       [-0.14502562, -0.10856887, -0.11219895],
       [-0.35194857, -0.02030146, -0.62441373]])

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [15]:
A=np.random.uniform(0,10,10)
A1=(A-A%1).astype(int)
A2=(A//1).astype(int)
print(A1)
print(A2)

[0 2 8 7 3 9 0 0 0 6]
[0 2 8 7 3 9 0 0 0 6]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [16]:
z = np.zeros((5,5)) + np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [12]:
z = np.random.random(10)
z.sort()
print(z)

[0.16073373 0.23451751 0.26906322 0.71196175 0.74732435 0.76433835
 0.78672936 0.89699182 0.9385523  0.99856986]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [25]:
A=np.random.randint(0,2,5)
B=np.random.randint(0,2,5)
print(A)
print(B)
print(np.array_equal(A,B))

[1 1 0 0 0]
[1 0 0 1 1]
False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [26]:
Z=np.random.random((10,2))

X=Z[:,0]
Y=Z[:,1]

R=np.sqrt(X**2+Y**2)
T=np.arctan2(Y,X)

polar=np.column_stack((R,T))

print(polar)

[[0.69964275 0.10710135]
 [0.81133222 1.51485879]
 [0.99406187 0.90480914]
 [0.7940187  1.56352596]
 [0.88138266 0.75314993]
 [1.03731726 0.49517252]
 [0.46242347 1.51351534]
 [0.6880912  0.21592815]
 [1.01420539 1.32061097]
 [1.12307069 0.57133584]]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [27]:
Z=np.random.random(10)
print(Z)
Z[Z.argmax()]=0
print(Z)

[0.55528174 0.89793322 0.79464605 0.20922959 0.15775958 0.47834893
 0.81781311 0.54292915 0.34614106 0.9524883 ]
[0.55528174 0.89793322 0.79464605 0.20922959 0.15775958 0.47834893
 0.81781311 0.54292915 0.34614106 0.        ]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [28]:
Z=np.arange(100)
v=np.random.uniform(0,100)
index=(np.abs(Z-v)).argmin()
print(Z[index])

62


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [29]:
Z=np.arange(9).reshape(3,3)

for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [30]:
n=5
p=3
Z=np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),1)
print(Z)

[[0. 1. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [32]:
Z=np.random.randint(0,10,(3,3))

print(Z[Z[:,0].argsort()])

[[2 4 4]
 [3 7 4]
 [8 4 8]]


In [33]:
print(Z[Z[:,1].argsort()])

[[2 4 4]
 [8 4 8]
 [3 7 4]]


In [34]:
print(Z[Z[:,2].argsort()])

[[2 4 4]
 [3 7 4]
 [8 4 8]]
